global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'pd'
    static_configs:
      - targets: ['127.0.0.1:12379']
    metrics_path: /metrics

  - job_name: 'tikv'
    static_configs:
      - targets: ['127.0.0.1:30180']
    metrics_path: /metrics


