{
 "title": "TiKV Starter",
 "tags": [ "tikv" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "TiKV gRPC QPS",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count[1m]))",
     "legendFormat": "grpc qps"
    }
   ]
  },
  {
   "title": "TiKV Storage Write Bytes/s",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(tikv_storage_async_write_bytes_sum[1m]))",
     "legendFormat": "write bytes/s"
    }
   ]
  },
  {
   "title": "TiKV Engine Bytes Read/Write",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(tikv_engine_bytes_written[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(tikv_engine_bytes_read[1m]))",
     "legendFormat": "read"
    }
   ]
  }
 ]
}